name: namer_app
description: "A new Flutter project."
# 以下の行は、`flutter pub publish`を使用して誤ってパッケージをpub.devに公開しないようにします。これは、プライベートパッケージには推奨されます。
publish_to: 'none' # この行を削除してpub.devに公開する場合は、この行を削除してください。

# 以下は、アプリケーションのバージョンとビルド番号を定義します。
# バージョン番号は、1.2.43のようにドットで区切られた3つの数字で構成されます
# オプションで、+で区切られたビルド番号が続きます。
# バージョンとビルド番号は、flutter buildで--build-nameと--build-numberを指定することで上書きできます。
# Androidでは、build-nameはversionNameとして使用され、build-numberはversionCodeとして使用されます。
# Androidのバージョニングについては、https://developer.android.com/studio/publish/versioningを参照してください。
# iOSでは、build-nameはCFBundleShortVersionStringとして使用され、build-numberはCFBundleVersionとして使用されます。
# iOSのバージョニングについては、https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.htmlを参照してください。
# Windowsでは、build-nameは製品およびファイルバージョンのメジャー、マイナー、およびパッチ部分として使用され、build-numberはビルドサフィックスとして使用されます。
version: 0.0.1+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# 依存関係は、パッケージが動作するために必要な他のパッケージを指定します。
# パッケージの依存関係を最新バージョンに自動的にアップグレードするには、`flutter pub upgrade --major-versions`を実行することを検討してください。または、
# 依存関係は、以下のバージョン番号を最新バージョンに変更することで手動で更新できます。
# より新しいバージョンが利用可能な依存関係を確認するには、`flutter pub outdated`を実行してください。
dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.1

  # 以下は、Cupertino Iconsフォントをアプリケーションに追加します。
  # iOSスタイルのアイコンにはCupertinoIconsクラスを使用します。
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # "flutter_lints"パッケージには、推奨されるリントのセットが含まれており、
  # 良いコーディングプラクティスを促進します。パッケージが提供するリントセットは、
  # パッケージのルートにある`analysis_options.yaml`ファイルでアクティブ化されます。
  # 特定のリントルールを非アクティブ化したり、追加のリントをアクティブ化するには、
  # そのファイルを参照してください。
  flutter_lints: ^3.0.0

# このファイルのDartの一般的な部分に関する情報については、
# 次のページを参照してください：https://dart.dev/tools/pub/pubspec

# 以下のセクションは、Flutterパッケージに固有です。
flutter:

  # 以下の行は、Material Iconsフォントが
  # アプリケーションに含まれるようにします。これにより、material Iconsクラスでアイコンを使用できます。
  uses-material-design: true

  # アプリケーションにアセットを追加するには、次のようにassetsセクションを追加します：
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 画像アセットは、解像度に応じた「バリアント」を参照できます。詳細については、
  # https://flutter.dev/assets-and-images/#resolution-awareを参照してください。

  # パッケージ依存関係からアセットを追加する方法については、
  # https://flutter.dev/assets-and-images/#from-packagesを参照してください。

  # アプリケーションにカスタムフォントを追加するには、ここにfontsセクションを追加します。
  # このリストの各エントリには、フォントファミリ名を持つ「family」キーと、
  # フォントのアセットおよびその他の記述子を指定する「fonts」キーが必要です。例：
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # パッケージ依存関係からのフォントの詳細については、
  # https://flutter.dev/custom-fonts/#from-packagesを参照してください。
